-- CaptureAI Database Schema
-- Canonical source of truth. For test data, use: api/seed.sql

DROP TABLE IF EXISTS subscription_events;
DROP TABLE IF EXISTS verification_codes;
DROP TABLE IF EXISTS webhook_events;
DROP TABLE IF EXISTS usage_breakdown;
DROP TABLE IF EXISTS usage_daily;
DROP VIEW IF EXISTS total_usage_daily;
DROP VIEW IF EXISTS user_usage;
DROP VIEW IF EXISTS total_usage;
DROP TABLE IF EXISTS users;

-- Users table
-- id is a UUID generated by the application (generateUUID())
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL COLLATE NOCASE UNIQUE,
  license_key TEXT UNIQUE NOT NULL,
  tier TEXT DEFAULT 'basic' CHECK (tier IN ('basic', 'pro')),
  subscription_status TEXT DEFAULT 'inactive' CHECK (subscription_status IN ('active', 'inactive', 'cancelled', 'past_due')),
  stripe_customer_id TEXT UNIQUE,
  stripe_subscription_id TEXT UNIQUE,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_stripe_subscription ON users(stripe_subscription_id);
CREATE INDEX idx_users_tier ON users(tier);
CREATE INDEX idx_users_subscription_status ON users(subscription_status);

-- Daily aggregated usage per user
-- Primary source for rate-limit checks (O(1) point-lookup by PK).
CREATE TABLE usage_daily (
  email TEXT NOT NULL,
  date TEXT NOT NULL,
  request_count INTEGER DEFAULT 0,
  cached_request_count INTEGER DEFAULT 0,
  input_tokens INTEGER DEFAULT 0,
  output_tokens INTEGER DEFAULT 0,
  total_cost REAL DEFAULT 0.0,
  PRIMARY KEY (email, date)
  -- Composite PK creates the index; no separate CREATE INDEX needed.
);

-- Per-day, per-prompt-type, per-model aggregates for analytics.
-- Replaces usage_records: writes are reliable (same transaction pattern as usage_daily).
CREATE TABLE usage_breakdown (
  email TEXT NOT NULL,
  date TEXT NOT NULL,
  prompt_type TEXT NOT NULL,
  model TEXT NOT NULL,
  request_count INTEGER DEFAULT 0,
  cached_count INTEGER DEFAULT 0,
  input_tokens INTEGER DEFAULT 0,
  output_tokens INTEGER DEFAULT 0,
  total_cost REAL DEFAULT 0.0,
  total_response_time INTEGER DEFAULT 0,
  PRIMARY KEY (email, date, prompt_type, model)
  -- Composite PK creates the index; no separate CREATE INDEX needed.
);

-- Stripe event deduplication to prevent replay attacks.
-- Rows older than 24 hours are pruned after each webhook delivery.
CREATE TABLE webhook_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id TEXT UNIQUE NOT NULL,
  event_type TEXT NOT NULL,
  processed_at TEXT NOT NULL DEFAULT (datetime('now')),
  webhook_timestamp TEXT NOT NULL
);

-- Email OTP codes for login and tier-switch verification (10-min TTL).
-- Rows are purged by the daily cron.
CREATE TABLE verification_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  code TEXT NOT NULL,
  action TEXT NOT NULL,
  tier TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0 CHECK (used IN (0, 1))
);

-- Covers the hot lookup: WHERE email=? AND action=? AND code=? AND used=0 AND expires_at > now()
CREATE INDEX idx_verification_codes_lookup ON verification_codes(email, action, code, used, expires_at);

-- Immutable audit log of every subscription state change.
-- One row per event; never updated or deleted.
CREATE TABLE subscription_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  event_type TEXT NOT NULL,
  from_tier TEXT,
  to_tier TEXT,
  from_status TEXT,
  to_status TEXT,
  stripe_event_id TEXT,
  metadata TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_subscription_events_email ON subscription_events(email, created_at);

-- Admin view: usage totals at three levels of granularity (reads usage_breakdown).
--   sort_order 1 = grand total
--   sort_order 2 = per prompt_type
--   sort_order 3 = per model
CREATE VIEW total_usage AS
SELECT
  1 AS sort_order,
  'ALL' AS prompt_type,
  'ALL' AS model,
  COALESCE(SUM(request_count), 0) AS requests,
  COALESCE(SUM(input_tokens), 0) AS input_tokens,
  COALESCE(SUM(output_tokens), 0) AS output_tokens,
  ROUND(COALESCE(SUM(total_cost), 0.0), 8) AS total_cost
FROM usage_breakdown

UNION ALL

SELECT
  2 AS sort_order,
  prompt_type,
  'ALL' AS model,
  COALESCE(SUM(request_count), 0) AS requests,
  COALESCE(SUM(input_tokens), 0) AS input_tokens,
  COALESCE(SUM(output_tokens), 0) AS output_tokens,
  ROUND(COALESCE(SUM(total_cost), 0.0), 8) AS total_cost
FROM usage_breakdown
GROUP BY prompt_type

UNION ALL

SELECT
  3 AS sort_order,
  'ALL' AS prompt_type,
  model,
  COALESCE(SUM(request_count), 0) AS requests,
  COALESCE(SUM(input_tokens), 0) AS input_tokens,
  COALESCE(SUM(output_tokens), 0) AS output_tokens,
  ROUND(COALESCE(SUM(total_cost), 0.0), 8) AS total_cost
FROM usage_breakdown
GROUP BY model;

-- Per-user usage statistics
CREATE VIEW user_usage AS
SELECT
  email,
  COALESCE(SUM(request_count), 0) AS requests,
  COALESCE(SUM(input_tokens), 0) AS input_tokens,
  COALESCE(SUM(output_tokens), 0) AS output_tokens,
  ROUND(COALESCE(SUM(total_cost), 0.0), 8) AS total_cost
FROM usage_breakdown
GROUP BY email;

-- Admin summary from daily aggregates (authoritative totals)
CREATE VIEW total_usage_daily AS
SELECT
  COALESCE(SUM(request_count), 0) AS requests,
  COALESCE(SUM(cached_request_count), 0) AS cached_requests,
  COALESCE(SUM(input_tokens), 0) AS input_tokens,
  COALESCE(SUM(output_tokens), 0) AS output_tokens,
  ROUND(COALESCE(SUM(total_cost), 0.0), 8) AS total_cost
FROM usage_daily;
